### ISSUE TITLE
使用新的exfat模块

### ISSUE THREAD

**Issue by ywgf88** [Cathgao/GDOCK-Cath#2]
大神好，有个问题想咨询你:每次编译不成功你都能第一时间知道root cause,想了解一下你是怎么发现这个根因的？

**Comment by Cathgao** [comment]
> 大神好，有个问题想咨询你:每次编译不成功你都能第一时间知道root cause,想了解一下你是怎么发现这个根因的？

查看编译日志，找到有error的地方，看看是什么问题
