### ISSUE TITLE
太大了，200m的固件

### ISSUE THREAD

**Issue by zhubinsheng** [Cathgao/GDOCK-Cath#5]
可以做两个make，一个精简版 一个full版

**Comment by Cathgao** [comment]
> 可以做两个make，一个精简版 一个full版
固件就64MB不到，何来太大一说呢
![QQ截图20210914140420](https://user-images.githubusercontent.com/21031564/133203624-8ef2bc0a-4c09-4744-a80e-66b8f955cad0.png)

**Comment by zhubinsheng** [comment]
感谢回复 第一次编译这个 不知道里面有三个编译产物
